import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "outline-variant": "#564334",
        "inverse-surface": "#e5e2e1",
        border: "rgba(247, 247, 247, 0.1)",
        "on-tertiary": "#00344d",
        outline: "#a58c7b",
        "secondary-fixed": "#e2e2e2",
        "on-error": "#690005",
        error: "#ffb4ab",
        "on-tertiary-fixed-variant": "#004c6d",
        "on-surface-variant": "#d4b8a4",
        "on-background": "#e5e2e1",
        "primary-fixed-dim": "#ffb77f",
        "secondary-container": "#454747",
        "tertiary-fixed-dim": "#88ceff",
        "surface-dim": "#131313",
        "surface-container-highest": "#353534",
        "on-primary-fixed-variant": "#6f3900",
        "on-error-container": "#ffdad6",
        "on-primary-fixed": "#2f1500",
        "surface-variant": "#353534",
        primary: "#ffb77f",
        "on-secondary": "#2f3131",
        "secondary-fixed-dim": "#c6c6c7",
        "muted-text": "#7c7c7c",
        "inverse-on-surface": "#313030",
        "on-secondary-fixed": "#1a1c1c",
        "error-container": "#93000a",
        "tertiary-container": "#00b3fc",
        "primary-container": "#ff8a00",
        "on-secondary-container": "#b4b5b5",
        secondary: "#c6c6c7",
        "tertiary-fixed": "#c8e6ff",
        surface: "#121212",
        "surface-bright": "#3a3939",
        "primary-fixed": "#ffdcc4",
        "on-tertiary-fixed": "#001e2e",
        "on-primary": "#4e2600",
        "on-primary-container": "#613100",
        background: "#131313",
        "surface-container-lowest": "#0e0e0e",
        "on-secondary-fixed-variant": "#454747",
        "on-surface": "#e5e2e1",
        "surface-tint": "#ffb77f",
        "on-tertiary-container": "#004260",
        tertiary: "#88ceff",
        "surface-container": "#201f1f",
        "inverse-primary": "#914c00",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
        card: "24px",
      },
      spacing: {
        "stack-sm": "8px",
        "stack-md": "18px",
        "section-gap": "168px",
        "margin-safe": "clamp(1rem, 4.5vw, 5.5vw)",
        gutter: "clamp(16px, 2.5vw, 28px)",
        "stack-lg": "36px",
      },
      fontFamily: {
        sans: ["var(--font-sans)", "Inter", "sans-serif"],
        display: ["var(--font-display)", "Bebas Neue", "sans-serif"],
        "body-md": ["var(--font-sans)", "Inter", "sans-serif"],
        "headline-lg-mobile": ["var(--font-display)", "Bebas Neue", "sans-serif"],
        "label-mono": ["var(--font-sans)", "Inter", "sans-serif"],
        "display-lg": ["var(--font-display)", "Bebas Neue", "sans-serif"],
        "headline-lg": ["var(--font-display)", "Bebas Neue", "sans-serif"],
        "body-lg": ["var(--font-sans)", "Inter", "sans-serif"],
        "display-xl": ["var(--font-display)", "Bebas Neue", "sans-serif"],
      },
      fontSize: {
        "body-md": [
          "16px",
          { lineHeight: "28px", letterSpacing: "0.01em", fontWeight: "400" },
        ],
        "headline-lg-mobile": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "label-mono": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.12em", fontWeight: "500" },
        ],
        "display-lg": [
          "80px",
          { lineHeight: "78px", letterSpacing: "-0.035em", fontWeight: "800" },
        ],
        "headline-lg": [
          "48px",
          { lineHeight: "54px", letterSpacing: "-0.025em", fontWeight: "700" },
        ],
        "body-lg": [
          "20px",
          { lineHeight: "34px", letterSpacing: "0.01em", fontWeight: "400" },
        ],
        "display-xl": [
          "120px",
          { lineHeight: "108px", letterSpacing: "-0.045em", fontWeight: "800" },
        ],
      },
    },
  },
  plugins: [],
};

export default config;
